### ISSUE TITLE
Missing mxnet in text-preprocessing.ipynb

### ISSUE THREAD

**Issue by batram** [d2l-ai/d2l-en-colab#3]
The module mxnet is not installed in text-preprocessing.ipynb, but d2l tries to import it.

Opening chapter_recurrent-neural-networks/text-preprocessing.ipynb in colab running the first real code block throws the following error:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-2-ca39b75918e7> in <module>()
>       1 import collections
> ----> 2 import d2l
>       3 import re
>       4 
>       5 # Saved in the d2l package for later use
> 
> 1 frames
> /usr/local/lib/python3.6/dist-packages/d2l/d2l.py in <module>()
>      12 import math
>      13 from matplotlib import pyplot as plt
> ---> 14 from mxnet import autograd, context, gluon, image, init, np, npx
>      15 from mxnet.gluon import nn, rnn
>      16 import os
> 
> ModuleNotFoundError: No module named 'mxnet'
> ...

**Comment by StevenJokes** [comment]
fix now.
